spring:
  application:
    name: service-order


  server:
    port: 8080

  rabbitmq:
    host: localhost
    ports:
      - "5672:5672"
    username: guest
    password: guest

    listener:
      simple:
        concurrency: 5
        max-concurrency: 20
        prefetch: 5

  data:
    redis:
      host: localhost
      ports:
        - "6379:6379"
      timeout: 60000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2

    mongodb:
      uri: mongodb://localhost:27017/service_order_mongo


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    display-request-duration: true
    disable-swagger-default-url: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - caches
          - loggers
          - mappings
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    rabbit:
      enabled: true
    redis:
      enabled: true
    metrics:
      enable:
        all: true
